### ISSUE TITLE
Fehler beim Updaten

### ISSUE THREAD

**Issue by andrucha97** [vmario89/sysPass-update#1]
Wenn ich das Skript ausführe erhalte ich Errors.

Geholfen hat es das Skript anzupassen:
php composer.phar install
php composer.phar install 

in

php composer.phar install --no-dev
php composer.phar install --no-dev

Sowie

chown -R www-data:$SPUSER "$APP_PATH"/

in

chown -R www-data "$APP_PATH"/

**Comment by vmario89** [comment]
Hey, hast du mehr Details zu den Fehlermeldungen? Ich habe gerade einen Fehler gefixt - das composer Update konnte nicht laufen, weil "compuser" drin stand.

Mit den --no-dev Modus gibt es Probleme. Wenn dieser gewählt wird, wird das sysPass Authenticator Plugin automatisch deinstalliert und ist nicht mehr verfügbar. Die dev dependencies werden also benötigt.

Das Ändern der Rechte zu chown -R www-data "$APP_PATH"/ bewirkt, dass nur der User, nicht aber die Gruppe aktualisiert wird. Du kannst auch $SPUSER zu www-data setzen, dann sollte es problemfrei laufen.  Je nach Situation kann hier unterschiedlich gearbeitet werden. Ich habe für sysPass eine eigene Gruppe angelegt, weswegen ich den user zu "www-data" setze und die Gruppe zu "syspass".

Siehe auch https://serverfault.com/questions/357108/what-permissions-should-my-website-files-folders-have-on-a-linux-webserver

vG, Mario

**Comment by andrucha97** [comment]
Hey,

gerade getestet. Hast recht compuser hat die Fehler verursacht... hatte es nur einmal ausgeführt nach der Änderung und habe unbewusst diesen Fehler mit bearbeitet :D 

Wenn du doch chown -R www-data:$SPUSER "$APP_PATH"/ in chown -R www-data "$APP_PATH"/ änderst sollte er doch nur eins anpassen.... das alte bleibt doch oder?

Ansonsten läuft es jetzt gut

Andere Frage...
COMMIT=$(git ls-remote https://github.com/nuxsmin/sysPass.git refs/heads/devel-3.0|cut -c-40) 

Was kann ich tun um immer die neuste aus der Tags zu bekommen?
Würde gerne immer das neuste Release haben wollen

So ist es nicht die neuste
COMMIT=$(git ls-remote https://github.com/nuxsmin/sysPass.git refs/heads/3.0|cut -c-40) 

So muss ich immer wieder die neuste auswählen
COMMIT=$(git ls-remote https://github.com/nuxsmin/sysPass.git refs/tags/3.0.0.18111901-rc3|cut -c-40) 

VG, Andreas

**Comment by andrucha97** [comment]
Muss die letzte Frage zurücknehmen...
scheint so als würde gerade
COMMIT=$(git ls-remote https://github.com/nuxsmin/sysPass.git refs/heads/3.0|cut -c-40)
das neuste zu sein...

es gibt gerade die rc3 und bei branch 3.0 rc4

habe noch eine Sachen eingebaut schicke ich gleich in einem neuen Issue. :)

**Comment by andrucha97** [comment]
> Wenn du doch chown -R www-data:$SPUSER "$APP_PATH"/ in chown -R www-data "$APP_PATH"/ änderst sollte er doch nur eins anpassen.... das alte bleibt doch oder?

Schwachsinn :D jetzt verstehe ich was mit -ci im Skript gemeint ist.... cool gemacht! :)

**Comment by vmario89** [comment]
Hey. Das Script ist aktuell so ausgelegt, dass es das offizielle git repo klont und die Dateien verwendet, um die laufende Instanz im Produktionsordner zu upgraden (via rsync). Dabei bedient es sich also zunächst einer angegeben commit-id, auf die das geklonte Repo ausgecheckt wird. Der Branch ist dem Script komplett egal - nur der commit ist entscheidend. Letztlich kannst du somit zum Beispiel die alleraktuellste commid-id vom Masterbranch verwenden, oder eine commit-id eines offiziellen Releases. Siehe roter Rahmen im Screenshot 

![grafik](https://user-images.githubusercontent.com/5631071/48810575-5d07c600-ed2a-11e8-8ea0-a0f8f408b66e.png)

Du kannst übrigens die volle Länge des commits verwenden (in diesem Fall "afdfa80d8f545dbe39237b0e3266b490ea45062b"). Es reicht aber schon die Angabe der ersten 7 Zeichen (hier "afdfa80") zum Auschecken. 

Somit voll flexibel ;-) Du könntest sogar eine deutlich ältere Commit-ID verwenden. Allerdings könnte dein Datenbankmodell dann zu neu sein und die sysPass-Instanz wird dich mich Fehlern berühmen.

vG, Mario

**Comment by andrucha97** [comment]
jo hat sich bereits erledigt. :)
war nur ein Verständnis Problem bei Syspass wo gerade die aktuellste Version ist. Danke dir!
